name: Docs Metadata Checks

# Grant write permission so PR workflows can commit updated JSONs back
permissions:
  contents: write

on:
  pull_request: {}
  push:
    branches:
      - main
      - 'release/**'

jobs:
  uorb-graph-check:
    name: Check uORB graph JSONs
    runs-on: [runs-on,runner=4cpu-linux-x64,image=ubuntu22-full-x64,"run-id=${{ github.run_id }}",spot=true]
    container:
      image: ghcr.io/px4/px4-dev:v1.16.0-rc1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run uORB graph docs check
        run: Tools/ci/metadata_uorb_graph.sh --test-only --debug
