name: Docs Metadata Checks

permissions:
  contents: write

on:
  pull_request: {}
  push:
    branches:
      - main
      - 'release/**'

jobs:
  uorb-graph-check:
    name: Check uORB graph JSONs
    runs-on: [runs-on,runner=2cpu-linux-x64,image=ubuntu24-full-x64,"run-id=${{ github.run_id }}",spot=true]
    container:
      image: ghcr.io/px4/px4-dev:v1.16.0-rc1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Mark all directories safe for Git
        run: git config --system --add safe.directory '*'

      - name: Run uORB graph docs check
        run: Tools/ci/metadata_uorb_graph.sh --test-only

  failsafe-web-check:
    name: Check failsafe web metadata files
    runs-on: [runs-on,runner=2cpu-linux-x64,image=ubuntu24-full-x64,"run-id=${{ github.run_id }}",spot=true]
    container:
      image: ghcr.io/px4/px4-dev:v1.16.0-rc1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Mark all directories safe for Git
        run: git config --system --add safe.directory '*'

      - name: Run failsafe web metadata check
        run: Tools/ci/metadata_failsafe_web.sh --test-only

  msg-docs-check:
    name: Check uORB message reference docs
    runs-on: [runs-on,runner=2cpu-linux-x64,image=ubuntu24-full-x64,"run-id=${{ github.run_id }}",spot=true]
    container:
      image: ghcr.io/px4/px4-dev:v1.16.0-rc1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Mark all directories safe for Git
        run: git config --system --add safe.directory '*'

      - name: Run uORB message docs check
        run: Tools/ci/metadata_msg_docs.sh --test-only

  parameters-check:
    name: Check parameter reference metadata
    runs-on: [runs-on,runner=2cpu-linux-x64,image=ubuntu24-full-x64,"run-id=${{ github.run_id }}",spot=true]
    container:
      image: ghcr.io/px4/px4-dev:v1.16.0-rc1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Mark all directories safe for Git
        run: git config --system --add safe.directory '*'

      - name: Run parameter docs check
        run: Tools/ci/metadata_parameters.sh --test-only
